name: CreateAlphaDocumentation
env:
  FIREHUB_APP_TITLE: FireHub Web Application Framework
  FIREHUB_APP_NAME: Core
  FIREHUB_APP_VERSION: v0.2
  FIREHUB_BRANCH: v1.0
on:
  push:
    branches:
      - '*develop*alpha*'
  pull_request:
    branches:
      - '*develop*alpha*'
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "documentation"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache phpDocumentor build files
        id: phpdocumentor-cache
        uses: actions/cache@v3
        with:
          path: .phpdoc/cache
          key: ${{ runner.os }}-phpdocumentor-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-phpdocumentor-
      - name: Build Wiki with phpDocumentor
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --title "${FIREHUB_APP_TITLE}" --directory src --target docs/wiki --visibility public --setting="app_name=${FIREHUB_APP_NAME}" --setting="app_version=${FIREHUB_APP_VERSION}" --setting="branch=${FIREHUB_BRANCH}" --template vendor/firehub/documentor/src/template/wiki
      - name: Build Pages with phpDocumentor
        run: docker run --rm --volume "$(pwd):/data" phpdoc/phpdoc:3 -vv --title "${FIREHUB_APP_TITLE}" --directory src --target docs/pages --setting="app_name=${FIREHUB_APP_NAME}" --setting="app_version=${FIREHUB_APP_VERSION}" --setting="branch=${FIREHUB_BRANCH}" --template vendor/firehub/documentor/src/template/pages
      - name: Git Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add docs/
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git push
      - name: Push documentation
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.FIREHUB }}
        with:
          source-directory: 'docs/pages'
          destination-github-username: 'The-FireHub-Project'
          destination-repository-name: 'the-firehub-project.github.io'
          user-email: danijel.galic@outlook.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: master
          target-directory: 'core/v0.2'
      - name: Push Wiki Changes
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          WIKI_DIR: ./docs/wiki/
          GH_TOKEN: ${{ secrets.FIREHUB }}
          GH_MAIL: ${{ secrets.EMAIL }}
          GH_NAME: ${{ github.repository_owner }}