name: PHPStan
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          php_version: 8.1
          configuration: phpstan.neon
          memory_limit: 256M